#ifndef IRUDI_GUZTIAK_H
#define IRUDI_GUZTIAK_H

#define JOKOA_PLAYER_IMAGE ".\\img\\Skin.bmp"
#define LAPURRA_TESTUA ".\\img\\lapurra.bmp"
#define ETXEAREN_PREZIOA ".\\img\\1000.bmp"
#define BANKUAREN_PREZIOA ".\\img\\3000.bmp"
#define HOSPITALAREN_PREZIOA ".\\img\\2000.bmp"
#define MERKATUAREN_PREZIOA ".\\img\\500.bmp"
#define UDALETXEAREN_PREZIOA ".\\img\\10000.bmp"
#define EDIFIZIOA_HOBETUTA_DAGO ".\\img\\etxe hau hobetuta dago.bmp"
#define ETXEA1_APURTUTA ".\\img\\etxea1_apurtuta.bmp"
#define ETXEA1_KONPONDUTA ".\\img\\etxea1_konponduta.bmp"
#define ETXEA2_KONPONDUTA ".\\img\\etxea2_konponduta.bmp"
#define BANKUA_APURTUTA ".\\img\\bankua_apurtuta.bmp"
#define BANKUA_KONPONDUTA ".\\img\\bankua_konponduta.bmp"
#define HOSPITALEA_APURTUTA ".\\img\\hospitalea_apurtuta.bmp"
#define HOSPITALEA_KONPONDUTA ".\\img\\hospitalea_konponduta.bmp"
#define MERKATUA_APURTUTA ".\\img\\merkatua_apurtuta.bmp"
#define MERKATUA_KONPONDUTA ".\\img\\merkatua_konponduta.bmp"
#define UDALETXEA_APURTUTA ".\\img\\udaletxea_apurtuta.bmp"
#define ESKOLA_KONPONDUTA ".\\img\\eskola_konponduta.bmp"
#define ETXEA3_KONPONDUTA ".\\img\\etxea3_konponduta.bmp"
#define KEBAB_KONPONDUTA ".\\img\\EDIFICIO_KEBAB_140x.bmp"
#define UNIBERTSITATEA_KONPONDUTA ".\\img\\unibertsitatea_konponduta.bmp"
#define KIROLDEGIA_KONPONDUTA ".\\img\\polideportivo_150x.bmp"
#define ZENTRAL_ELEKTRIKOA_KONPONDUTA ".\\img\\Zentrala_170x.bmp"
#define ESKOLA_PREZIOA ".\\img\\H ESKOLA.bmp"
#define ETXEA3_PREZIOA ".\\img\\H Etxea.bmp"
#define KEBAB_PREZIOA ".\\img\\H KEBAB.bmp"
#define UNIBERTSITATEA_PREZIOA ".\\img\\H UNI.bmp"
#define KIROLDEGIA_PREZIOA ".\\img\\H KIROLDEGI.bmp"
#define ZENTRAL_ELEKTRIKOA_PREZIOA ".\\img\\H ZENTRAL.bmp"
#define ERREKOLEKTOREA ".\\img\\errekolektorea.bmp"
#define HOBEKUNTZA_GUZTIAK_DITUZU ".\\img\\hobekuntza guztiak dituzu.bmp"
#define ERAIKIN_GUZTIAK_DITUZU ".\\img\\ERAIKIN GUZTIAK DITUZU.bmp"
#define ATZEALDEA ".\\img\\fondo.bmp"
#define DIRURIK_EZ ".\\img\\Aholkuak-1.bmp"
#define AHOLKUAK_HUTZIK ".\\img\\Aholkuak-2.bmp"
#define BIZTANLEAK_HILTZEN ".\\img\\Aholkuak-3.bmp"
#define HEZKUNTZA_MAILA_BAXUA ".\\img\\Aholkuak-4.bmp"
#define MENUA ".\\img\\menu.bmp"
#define EZARPENAK ".\\img\\ezarpenak.bmp"
#define KREDITUAK ".\\img\\KREDITUAK.bmp"
#define IXA ".\\img\\ixa.bmp"
#define MUSIKA_AUKERATU ".\\img\\MUSIKA AUKERATU BMP.bmp"
#define GAME_OVER ".\\img\\gameOver.bmp"
#define IRABAZI_PANTAILA ".\\img\\irabazi.bmp"
#define TUTORIALA12 ".\\img\\TUTORIALA12.bmp"
#define TUTORIALA34 ".\\img\\TUTORIALA34.bmp"
#define TUTORIALA5 ".\\img\\TUTORIALA5.bmp"
#define TUTORIALA6 ".\\img\\TUTORIALA6.bmp"


#endif